import { Source_Sans_3 } from "next/font/google";
import "./globals.css";

const source_sans_3 = Source_Sans_3({ subsets: ["latin"] });

export const metadata = {
  title: "MUICT DevClub Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={source_sans_3.className}>{children}</body>
    </html>
  );
}
